### PR TITLE
Remove unnecessary register

### PR DESCRIPTION
**Pull request by lbischof**

### CODE REVIEW

**Comment by otakup0pe** [comment]
Why is that test unnecessary ?

**Comment by lbischof** [comment]
I am not exactly sure. That was a long time ago. I'm not exactly sure what this pull request does anymore... If you want I can have a look tomorrow or we can close this.

**Comment by otakup0pe** [comment]
I meant the idempotence test in the travis config.

**Comment by lbischof** [comment]
I don't think that's needed. Don't remember the reason I added it though.

**Comment by otakup0pe** [comment]
Unless I'm missing something, we want to keep the test. We want to ensure that these roles are actually idempotent.

**Comment by lbischof** [comment]
I agree

**Comment by wadik** [comment]
Please, merge this pull request!

**Comment by otakup0pe** [comment]
This has been fixed properly here https://github.com/ANXS/build-essential/pull/10

**Pull request closed without merging**
