### PR TITLE
Do not use loop on package module with squash_actions

### PR DESCRIPTION
**Pull request by arhue**
Fix deprecated warnings with Ansible 2.7

### CODE REVIEW

**Comment by otakup0pe** [comment]
Ha I was just making this PR myself. If you can update the min ansible version in `meta.yml` I'll merge yours instead 💖

**Comment by arhue** [comment]
@otakup0pe Done!

**Comment by otakup0pe** [comment]
Hmm reading https://docs.ansible.com/ansible/devel/porting_guides/porting_guide_2.7.html I thought that this syntax wasn't supported until 2.7 ? If it's 2.3 that'll make this transition easier for a lot of people.

**Comment by arhue** [comment]
@otakup0pe See if it looks ok now. Should I remove 1.9 and 2.0 as versions to test against? I've just added 2.3 and 2.7 to that list without removing anything.

**Comment by otakup0pe** [comment]
Since we only support 2.3 and above, that's all we should test against. Interesting that the tests pass but then again we aren't really _validating_ that the changes are what we want.

**Comment by arhue** [comment]
@otakup0pe Change made as suggested.

**Pull request merged**
